---
builds:
  - main: "./cmd/spicedb"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
      - "windows"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - "-s -w"
      - "-X {{ .ModulePath }}/internal/version.Version={{ .Version }}"
nfpms:
  - vendor: "authzed inc."
    homepage: "https://spicedb.io"
    maintainer: "authzed <support@authzed.com>"
    description: "SpiceDB is a Zanzibar-inspired database that stores, computes, and validates application permissions."
    license: "Apache 2.0"
    epoch: 0
    formats:
      - "apk"
      - "deb"
      - "rpm"
brews:
  - tap:
      owner: "authzed"
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/authzed/spicedb/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: "CurlDownloadStrategy"
    commit_author:
      name: "authzedbot"
      email: "infrastructure@authzed.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://authzed.com/"
    description: "SpiceDB is a Zanzibar-inspired database that stores, computes, and validates application permissions."
    license: "Apache-2.0"
    folder: "Formula"
    custom_block: |
      head "https://github.com/authzed/spicedb.git", :branch => "main"
    dependencies:
      - name: "go"
        type: "build"
    test: |
      system "#{bin}/spicedb version"
    install: |
      if !File.exists? "spicedb"
        system "go build --ldflags \"-s -w -X github.com/authzed/spicedb/internal/version.Version=$(git describe --always --abbrev=7 --dirty)\" ./cmd/spicedb"
      end
      bin.install "spicedb"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: "asc"
release:
  draft: true
  prerelease: "auto"
