name: "Release"
on:
  push:
    tags:
    - '*'
permissions:
  contents: write
jobs:
  docker:
    name: "Publish Container Image"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "docker/setup-qemu-action@v1"
    - uses: "docker/setup-buildx-action@v1"
      with:
        driver-opts: "image=moby/buildkit:master"
    - uses: "docker/login-action@v1"
      with:
        registry: "quay.io"
        username: ${{ secrets.QUAYIO_USER }}
        password: ${{ secrets.QUAYIO_PASSWORD }}
    - uses: "battila7/get-version-action@v2"
      id: get_version
    - uses: "docker/build-push-action@v2"
      with:
        push: true
        tags: |
          quay.io/authzed/spicedb:latest
          quay.io/authzed/spicedb:${{ steps.get_version.outputs.version }}
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.17"
    - uses: "goreleaser/goreleaser-action@v2"
      with:
        distribution: "goreleaser"
        version: "latest"
        args: "release --rm-dist"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
